-- MathsExpress v11.5.7 teacher safety alerts
create table if not exists public.mathsexpress_teacher_safety_alerts (
  id bigint generated by default as identity primary key,
  student_id uuid not null references auth.users(id) on delete cascade,
  class_id uuid references public.mathrift_classes(id) on delete cascade,
  school_id uuid references public.mathrift_schools(id) on delete cascade,
  category text not null check (category in ('profanity','harassment','threat','integrity','other')),
  severity text not null default 'medium' check (severity in ('low','medium','high')),
  source text not null, snippet text not null default '', details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), reviewed_at timestamptz, reviewed_by uuid references auth.users(id) on delete set null
);
create index if not exists mathsexpress_teacher_safety_alerts_school_created_idx on public.mathsexpress_teacher_safety_alerts(school_id, created_at desc);
alter table public.mathsexpress_teacher_safety_alerts enable row level security;
revoke all on table public.mathsexpress_teacher_safety_alerts from anon, authenticated;

create or replace function public.mathsexpress_create_safety_alert(p_class_id uuid,p_category text,p_source text,p_snippet text,p_severity text default 'medium',p_details jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare v_uid uuid:=auth.uid(); v_class uuid; v_school uuid; v_category text:=lower(trim(coalesce(p_category,'other'))); v_severity text:=lower(trim(coalesce(p_severity,'medium'))); v_source text:=left(trim(coalesce(p_source,'site')),80); v_snippet text:=left(regexp_replace(trim(coalesce(p_snippet,'')),'[[:space:]]+',' ','g'),300); v_id bigint;
begin
 if v_uid is null then raise exception 'Sign in required'; end if;
 if coalesce((select role from public.account_profiles where user_id=v_uid),'')<>'player' then return jsonb_build_object('ok',false,'ignored',true,'reason','student-only'); end if;
 if v_category not in ('profanity','harassment','threat','integrity','other') then v_category:='other'; end if; if v_severity not in ('low','medium','high') then v_severity:='medium'; end if;
 if p_class_id is not null and private.mathrift_in_class(p_class_id) then v_class:=p_class_id; else select m.class_id into v_class from public.mathrift_class_members m where m.student_id=v_uid order by m.joined_at desc limit 1; end if;
 if v_class is null then return jsonb_build_object('ok',false,'ignored',true,'reason','no-class'); end if; select c.school_id into v_school from public.mathrift_classes c where c.id=v_class; if v_school is null then return jsonb_build_object('ok',false,'ignored',true,'reason','no-school'); end if;
 if exists(select 1 from public.mathsexpress_teacher_safety_alerts a where a.student_id=v_uid and a.class_id=v_class and a.category=v_category and a.source=v_source and a.snippet=v_snippet and a.created_at>now()-interval '5 minutes') then return jsonb_build_object('ok',true,'duplicate',true); end if;
 insert into public.mathsexpress_teacher_safety_alerts(student_id,class_id,school_id,category,severity,source,snippet,details) values(v_uid,v_class,v_school,v_category,v_severity,v_source,v_snippet,coalesce(p_details,'{}'::jsonb)) returning id into v_id; return jsonb_build_object('ok',true,'id',v_id);
end $$;

create or replace function public.mathsexpress_teacher_safety_alerts(p_school_id uuid,p_limit integer default 50) returns table(id bigint,student_id uuid,student_name text,student_email text,class_id uuid,class_name text,category text,severity text,source text,snippet text,details jsonb,created_at timestamptz,reviewed_at timestamptz) language plpgsql security definer set search_path='public','private','pg_temp' as $$
begin if auth.uid() is null then raise exception 'Sign in required'; end if; if not private.mathrift_is_owner() and not exists(select 1 from public.mathrift_classes c where c.school_id=p_school_id and private.mathrift_teaches(c.id)) then raise exception 'Teacher access required'; end if; return query select a.id,a.student_id,p.display_name,p.email,a.class_id,c.name,a.category,a.severity,a.source,a.snippet,a.details,a.created_at,a.reviewed_at from public.mathsexpress_teacher_safety_alerts a left join public.account_profiles p on p.user_id=a.student_id left join public.mathrift_classes c on c.id=a.class_id where a.school_id=p_school_id order by (a.reviewed_at is null) desc,a.created_at desc limit greatest(1,least(200,coalesce(p_limit,50))); end $$;

create or replace function public.mathsexpress_review_safety_alert(p_alert_id bigint) returns jsonb language plpgsql security definer set search_path='public','private','pg_temp' as $$
declare v_class uuid; begin if auth.uid() is null then raise exception 'Sign in required'; end if; select class_id into v_class from public.mathsexpress_teacher_safety_alerts where id=p_alert_id; if v_class is null then raise exception 'Alert not found'; end if; if not (private.mathrift_is_owner() or private.mathrift_teaches(v_class)) then raise exception 'Teacher access required'; end if; update public.mathsexpress_teacher_safety_alerts set reviewed_at=coalesce(reviewed_at,now()),reviewed_by=coalesce(reviewed_by,auth.uid()) where id=p_alert_id; return jsonb_build_object('ok',true,'id',p_alert_id); end $$;
grant execute on function public.mathsexpress_create_safety_alert(uuid,text,text,text,text,jsonb) to authenticated;
grant execute on function public.mathsexpress_teacher_safety_alerts(uuid,integer) to authenticated;
grant execute on function public.mathsexpress_review_safety_alert(bigint) to authenticated;
